trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: 
  image: python:3.7
  options: -u root

steps:

- task: DownloadSecureFile@1
  name: SettingProfile
  displayName: 'Downloading Profile for Snowflake'
  inputs:
    secureFile: 'mysnowflake-db-wc70929_1'

- script: |
    echo Installing $(SettingProfile.secureFilePath) to the ~/.dbt...
    mkdir ~/.dbt
    cp $(SettingProfile.secureFilePath) ~/.dbt/profiles.yml
  displayName: Installing Profile for Snowflake
    
- script: |
    pip install dbt --user
    export PATH=$PATH:/home/vsts_azpcontainer/.local/bin
    cd snowflake_tpc_demo
    dbt compile
  displayName: 'Dbt project is Compiling'

- script: |
    cd snowflake_tpc_demo
    dbt test
    dbt run
  displayName: 'Dbt project is being Tested, and Run'